SELECT CART_ID FROM CART_PRODUCTS
WHERE CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME="Milk" AND CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME="Yogurt")) --2중 서브쿼리
GROUP BY CART_ID